server:
  port: 8082
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db8_springboot ?useSSL=false&serverTimezone=GMT
    username: root
    password: root
  application:
    name: user-service
eureka:
  client:
    service-url:            # 注册
      defaultZone: http://127.0.0.1:8090/eureka/,http://127.0.0.1:8091/eureka/
#    register-with-eureka: true    # 开启就注册，false不注册
  instance:
    lease-expiration-duration-in-seconds: 10  # 失效时间10s，默认90
    lease-renewal-interval-in-seconds: 5      # 心跳时间5s，默认30
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  configuration:
    map-underscore-to-camel-case: true    # 驼峰
  mapper-locations: mapper/*.xml          # xml文件配置 resource下的mapper包下，一般配置多表操作，单表不用
  type-aliases-package: cn.kk.pojo        # 别名包
  # 扫描mapper，在启动类上加 @MapperScan