server:
  port: 8900

spring:
  application:
    name: zuul-server

# 路由规则 setRoutes(Map<String, ZuulProperties.ZuulRoute>
zuul:
  routes:
    hehe-user-service:
      path: /user-service/**
#      url: http://localhost:8084   #这是写死的
      serviceId: user-service       # 这是通过eureka去寻找服务
#      strip-prefix: false
    call-user-server: /call-consumer/**
  ignored-services:     # setIgnoredServices(Set<String> ignoredServices)
      - call-user-server
#  strip-prefix: false
#    hehe-consumer:
#      path: /call-consumer/**
#      serviceId: call-user-server





# 配置eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8091/eureka/,http://127.0.0.1:8090/eureka/